#server:
#  port: 9000
#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.218.2:3306/eservice_oms
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: eservice-order
#  cloud:
#    nacos:
#      discovery:
#        ##server-addr: 192.168.218.2:8848
#        server-addr: localhost:8848
#mybatis-plus:
#  mapper-locations: classpath:/mapper/order/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
#



spring:
  session:
    store-type: redis
  rabbitmq:
    host: 192.168.218.2
    port: 5672
    # 虚拟主机
    virtual-host: /
    # 开启发送端发送确认，无论是否到达broker都会触发回调【发送端确认机制+本地事务表】
    publisher-confirm-type: correlated
    # 开启发送端抵达队列确认，消息未被队列接收时触发回调【发送端确认机制+本地事务表】
    publisher-returns: true
#    # 消息在没有被队列接收时是否强行退回
#    template:
#      mandatory: true
    # 消费者手动确认模式，关闭自动确认，否则会消息丢失
    listener:
      simple:
        acknowledge-mode: manual
  data:
    redis:
      host: 192.168.218.2
      port: 6379

eservicemall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10


